//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipeOrfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidat()
        {
            this.Consultant = new HashSet<Consultant>();
            this.Stage = new HashSet<Stage>();
        }
    
        public int CandidatID { get; set; }
        public string Prenom { get; set; }
        public string Nom { get; set; }
        public string Courriel { get; set; }
        public string Telephone { get; set; }
        public string TypePoste { get; set; }
        public string ProgrammeEtudes { get; set; }
        public string Etablissement { get; set; }
        public string Disponibilite { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public string Remarques { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consultant> Consultant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stage> Stage { get; set; }
    }
}
