//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipeOrfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultant
    {
        public int ConsultantID { get; set; }
        public Nullable<int> CandidatID { get; set; }
        public Nullable<decimal> TarifHoraire { get; set; }
        public string TypeContrat { get; set; }
        public string DureeMandat { get; set; }
    
        public virtual Candidat Candidat { get; set; }
    }
}
