//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipeOrfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeuresTravaillees
    {
        public int HeureID { get; set; }
        public string UserId { get; set; }
        public System.DateTime DateTravail { get; set; }
        public decimal NombreHeures { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
