//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipeOrfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage
    {
        public int StageID { get; set; }
        public Nullable<int> CandidatID { get; set; }
        public string ProgrammeScolaire { get; set; }
        public Nullable<bool> EncadrementRequis { get; set; }
        public string Duree { get; set; }
        public string Objectifs { get; set; }
    
        public virtual Candidat Candidat { get; set; }
    }
}
